<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>

        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>
        <AssemblyName>CodingDojo.Test</AssemblyName>
        <RootNamespace>CodingDojo.Test</RootNamespace>
        <Company>CodingDojo.Test</Company>
        <Product>CodingDojo.Test</Product>
        <Description></Description>
        <PackageLicenseUrl></PackageLicenseUrl>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="coverlet.collector" Version="8.0.0">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0"/>
        <PackageReference Include="NFluent" Version="3.1.0"/>
        <PackageReference Include="NUnit" Version="4.5.1"/>
    </ItemGroup>


    <ItemGroup>
        <ProjectReference Include="..\HeroQuest\HeroQuest.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <Folder Include="obj\Debug\net8.0\"/>
    </ItemGroup>

</Project>
